### ISSUE TITLE
docker stack deploy -c docker-compose.yml dev not working

### ISSUE THREAD

**Issue by basestring3** [jasonmccreary/local-docker-stack#1]
Hi,

When running docker stack deploy -c docker-compose.yml dev
getting error

Creating secret dev_db_pwd
open /Users/berry/apache/vhosts.conf: no such file or directory

your apache folder is missing the vhosts.conf file

struggling many days now but cant find a solution that work,
When adding vhosts.conf works, but server wont work, can't open my local site

**Comment by jasonmccreary** [comment]
This file is generated by [consolidate-vhosts.sh script](https://github.com/jasonmccreary/local-docker-stack/blob/master/apache/consolidate-vhosts.sh). You are welcome to tweak this to generate your own vhost file with your own vhosts.

**Comment by stianjaco2** [comment]
I get the same error, seems like that scripts does not run?

**Comment by jasonmccreary** [comment]
You'll have to update the script for your own environment. This repo is an example, not a ready-to-run environment.
