### ISSUE TITLE
consolidate-vhosts.sh refers to *.conf files that don’t exist

### ISSUE THREAD

**Issue by rosiemck** [jasonmccreary/local-docker-stack#2]
This command in consolidate-vhosts.sh 
cat ~/workspace/vhosts/*.conf > vhosts.conf

assumes that (a) there is a vhosts dir, and (b) it contains .conf files.

When I run it as is I get a 0B vhosts.conf file which stops everything from working.

Where do I find the appropriate .conf files?

Also, I amended the 1st line to:
#!/usr/bin/env bash

To allow for zsh environments (default in Catalina).

Also—thanks very much for your blog!

**Comment by jasonmccreary** [comment]
@rosiemck, you have to remember these are _my_ scripts. They are provided as a template or starting point. You'll need to make adjustments for your setup.

This script simply reads any of the `.conf` files from my local `~/workspace/vhosts/` directory and combines them into a single `vhosts.conf` file. This single file is mapped within my Docker stack so Apache is configured for my projects.

Based on that description, hopefully you may adjust for you local setup.
