### ISSUE TITLE
vhosts error, exiting lamp

### ISSUE THREAD

**Issue by mv-stns** [jasonmccreary/local-docker-stack#5]
<img width="1382" alt="CleanShot 2022-09-14 at 11 04 55@2x" src="https://user-images.githubusercontent.com/21103251/190111533-eda1c778-0201-4243-ae7a-5b3cef421d36.png">
Creating a vhosts.conf file in apache directory (since its needed) doesnt work

**Comment by ajmakoni** [comment]
@mv-stns incase you are still facing this issue, to fix it, create a file vhosts.conf inside apache folder and paste this content: 
`<VirtualHost _default_:*>
    DocumentRoot "/var/www/"
</VirtualHost>`
after that, deploy your stack
